server {
    listen 80;
    server_name localhost;

    # Directorio donde Docker guarda los archivos de Angular
    root /usr/share/nginx/html;
    index index.html;

    # 1. NUNCA CACHEAR EL INDEX.HTML (Fuerza siempre a buscar actualizaciones de la app)
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        expires off;
        try_files $uri /index.html;
    }

    # 2. CACHEAR ARCHIVOS COMPILADOS (Los .js y .css de Angular tienen hash único, son seguros)
    location ~* \.(?:css|js|jpg|jpeg|svg|png|woff2|woff|ttf|ico)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # 3. COMPORTAMIENTO POR DEFECTO PARA RUTAS DE ANGULAR
    location / {
        try_files $uri $uri/ /index.html;
    }
}